// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-daily-checkins.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.23.8";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_daily_checkins_default = defineTool({
  name: "list_daily_checkins",
  title: "List daily check-ins",
  description: "List the signed-in user's daily health check-in records, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(90).default(14).describe("Maximum number of records to return (1-90).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client(ctx).from("daily_checkins").select("*").eq("user_id", ctx.getUserId()).order("checkin_date", { ascending: false }).limit(limit);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { rows: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-meniere-records.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.23.8";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_meniere_records_default = defineTool2({
  name: "list_meniere_records",
  title: "List Meniere records",
  description: "List the signed-in user's Meniere / dizziness symptom records, most recent first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(20).describe("Max records to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client2(ctx).from("meniere_records").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { rows: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-diabetes-records.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.23.8";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_diabetes_records_default = defineTool3({
  name: "list_diabetes_records",
  title: "List diabetes records",
  description: "List the signed-in user's blood glucose / diabetes records, most recent first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(20).describe("Max records to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client3(ctx).from("diabetes_records").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { rows: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-medications.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_medications_default = defineTool4({
  name: "list_medications",
  title: "List medications",
  description: "List the signed-in user's active medications and dosage schedule.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client4(ctx).from("user_medications").select("*").eq("user_id", ctx.getUserId());
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { rows: data ?? [] } };
  }
});

// src/lib/mcp/tools/get-latest-weekly-report.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_latest_weekly_report_default = defineTool5({
  name: "get_latest_weekly_report",
  title: "Get latest AI weekly report",
  description: "Return the signed-in user's most recent AI-generated weekly health report (summary + suggestions).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client5(ctx).from("ai_weekly_reports").select("*").eq("user_id", ctx.getUserId()).order("week_start", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No weekly report available yet." }] };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { report: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ihwgygkrmwpcyrxcyzgh";
var mcp_default = defineMcp({
  name: "health-pal-mcp",
  title: "Health Pal",
  version: "0.1.0",
  instructions: "Tools for the signed-in Health Pal user: read daily check-ins, Meniere symptom logs, diabetes records, active medications, and the latest AI weekly health report. All tools are read-only and scoped to the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_daily_checkins_default,
    list_meniere_records_default,
    list_diabetes_records_default,
    list_medications_default,
    get_latest_weekly_report_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
