-- 插入更多英语单词
INSERT INTO english_words (word, pronunciation, meaning, example_sentence, example_translation, word_type, difficulty_level, frequency_rank) VALUES
('adventure', '/ədˈventʃər/', '冒险，奇遇', 'Life is an adventure waiting to be explored.', '生活是一场等待探索的冒险。', 'noun', 'intermediate', 6),
('beautiful', '/ˈbjuːtɪfl/', '美丽的，漂亮的', 'The sunset was absolutely beautiful tonight.', '今晚的日落绝对美丽。', 'adjective', 'beginner', 7),
('confident', '/ˈkɒnfɪdənt/', '自信的，确信的', 'She felt confident about her presentation.', '她对自己的演讲感到自信。', 'adjective', 'intermediate', 8),
('determined', '/dɪˈtɜːmɪnd/', '坚决的，下定决心的', 'He was determined to finish the marathon.', '他决心完成马拉松比赛。', 'adjective', 'intermediate', 9),
('enthusiastic', '/ɪnˌθjuːziˈæstɪk/', '热情的，热心的', 'The teacher was enthusiastic about the new project.', '老师对新项目很热心。', 'adjective', 'advanced', 10),
('flexible', '/ˈfleksəbl/', '灵活的，可弯曲的', 'You need to be flexible in your approach.', '你需要在方法上灵活一些。', 'adjective', 'intermediate', 11),
('generous', '/ˈdʒenərəs/', '慷慨的，大方的', 'She was generous with her time and help.', '她在时间和帮助上很慷慨。', 'adjective', 'intermediate', 12),
('honest', '/ˈɒnɪst/', '诚实的，正直的', 'He gave an honest answer to the question.', '他对这个问题给出了诚实的答案。', 'adjective', 'beginner', 13),
('innovative', '/ˈɪnəveɪtɪv/', '创新的，革新的', 'The company is known for its innovative products.', '这家公司以其创新产品而闻名。', 'adjective', 'advanced', 14),
('journey', '/ˈdʒɜːni/', '旅程，旅行', 'Learning a language is a long journey.', '学习语言是一个漫长的旅程。', 'noun', 'intermediate', 15),
('knowledge', '/ˈnɒlɪdʒ/', '知识，学问', 'Knowledge is power in today''s world.', '在当今世界，知识就是力量。', 'noun', 'intermediate', 16),
('leadership', '/ˈliːdəʃɪp/', '领导力，领导地位', 'Good leadership is essential for team success.', '良好的领导力对团队成功至关重要。', 'noun', 'advanced', 17),
('motivation', '/ˌməʊtɪˈveɪʃn/', '动机，积极性', 'His motivation comes from helping others.', '他的动力来自于帮助他人。', 'noun', 'advanced', 18),
('natural', '/ˈnætʃrəl/', '自然的，天然的', 'She has a natural talent for music.', '她有音乐天赋。', 'adjective', 'intermediate', 19),
('opportunity', '/ˌɒpəˈtjuːnəti/', '机会，时机', 'This job is a great opportunity for growth.', '这份工作是成长的好机会。', 'noun', 'intermediate', 20),
('passionate', '/ˈpæʃənət/', '热情的，激情的', 'She is passionate about environmental protection.', '她对环境保护充满热情。', 'adjective', 'advanced', 21),
('quality', '/ˈkwɒləti/', '质量，品质', 'The quality of this product is excellent.', '这个产品的质量很好。', 'noun', 'intermediate', 22),
('responsibility', '/rɪˌspɒnsəˈbɪləti/', '责任，职责', 'Taking care of pets is a big responsibility.', '照顾宠物是一个很大的责任。', 'noun', 'advanced', 23),
('solution', '/səˈluːʃn/', '解决方案，答案', 'We need to find a solution to this problem.', '我们需要找到这个问题的解决方案。', 'noun', 'intermediate', 24),
('tradition', '/trəˈdɪʃn/', '传统，惯例', 'Family dinner is an important tradition for us.', '家庭聚餐对我们来说是重要的传统。', 'noun', 'intermediate', 25),
('unique', '/juˈniːk/', '独特的，唯一的', 'Everyone has their own unique personality.', '每个人都有自己独特的个性。', 'adjective', 'intermediate', 26),
('valuable', '/ˈvæljuəbl/', '有价值的，宝贵的', 'Time is the most valuable resource we have.', '时间是我们拥有的最宝贵的资源。', 'adjective', 'intermediate', 27),
('wisdom', '/ˈwɪzdəm/', '智慧，明智', 'Age often brings wisdom and experience.', '年龄往往带来智慧和经验。', 'noun', 'advanced', 28),
('excellent', '/ˈeksələnt/', '优秀的，卓越的', 'Your performance was excellent today.', '你今天的表现很出色。', 'adjective', 'intermediate', 29),
('creative', '/kriˈeɪtɪv/', '创造性的，有创意的', 'She has a very creative approach to problem-solving.', '她在解决问题方面有很有创意的方法。', 'adjective', 'intermediate', 30),
('peaceful', '/ˈpiːsfl/', '和平的，平静的', 'The garden is a peaceful place to relax.', '花园是一个放松的宁静之地。', 'adjective', 'intermediate', 31),
('powerful', '/ˈpaʊəfl/', '强大的，有力的', 'Education is a powerful tool for change.', '教育是变革的有力工具。', 'adjective', 'intermediate', 32),
('reliable', '/rɪˈlaɪəbl/', '可靠的，可信赖的', 'He is a reliable friend who always helps.', '他是一个总是帮助别人的可靠朋友。', 'adjective', 'intermediate', 33),
('successful', '/səkˈsesfl/', '成功的，有成就的', 'Hard work often leads to successful outcomes.', '努力工作往往能带来成功的结果。', 'adjective', 'intermediate', 34),
('wonderful', '/ˈwʌndəfl/', '精彩的，极好的', 'We had a wonderful time at the party.', '我们在聚会上玩得很开心。', 'adjective', 'beginner', 35);

-- 插入更多英语短语
INSERT INTO english_phrases (phrase_english, phrase_chinese, meaning_explanation, example_sentence, example_translation, category, difficulty_level) VALUES
('break the ice', '打破僵局', '开始对话或缓解紧张气氛', 'He told a joke to break the ice at the meeting.', '他讲了个笑话来打破会议上的僵局。', 'idiom', 'intermediate'),
('piece of cake', '小菜一碟', '非常容易的事情', 'The math test was a piece of cake for her.', '数学考试对她来说是小菜一碟。', 'idiom', 'intermediate'),
('hit the books', '努力学习', '开始认真学习或阅读', 'I need to hit the books for my final exams.', '我需要为期末考试努力学习。', 'colloquial', 'intermediate'),
('under the weather', '身体不适', '感觉生病或不舒服', 'I''m feeling a bit under the weather today.', '我今天感觉有点不舒服。', 'idiom', 'intermediate'),
('spill the beans', '泄露秘密', '无意中透露秘密信息', 'Don''t spill the beans about the surprise party.', '不要泄露惊喜派对的秘密。', 'colloquial', 'intermediate'),
('cost an arm and a leg', '很昂贵', '价格非常高昂', 'That designer bag costs an arm and a leg.', '那个设计师包包非常昂贵。', 'idiom', 'advanced'),
('once in a blue moon', '千载难逢', '非常罕见或很少发生', 'We only see each other once in a blue moon.', '我们很少见面。', 'idiom', 'advanced'),
('the ball is in your court', '该你行动了', '轮到你做决定或采取行动', 'I''ve made my offer, now the ball is in your court.', '我已经提出了我的条件，现在该你行动了。', 'business', 'advanced'),
('let the cat out of the bag', '泄露秘密', '意外地透露了秘密', 'She let the cat out of the bag about the promotion.', '她无意中泄露了晋升的秘密。', 'colloquial', 'intermediate'),
('bite the bullet', '咬紧牙关', '勇敢面对困难或不愉快的情况', 'We have to bite the bullet and cut costs.', '我们必须咬紧牙关削减成本。', 'idiom', 'advanced'),
('go the extra mile', '付出额外努力', '做超出期望的事情', 'She always goes the extra mile for her customers.', '她总是为顾客付出额外的努力。', 'business', 'intermediate'),
('keep your chin up', '保持乐观', '在困难时期保持积极态度', 'Keep your chin up, things will get better.', '保持乐观，事情会好转的。', 'colloquial', 'intermediate'),
('turn over a new leaf', '重新开始', '改变行为，开始新的生活方式', 'After the accident, he turned over a new leaf.', '事故后，他重新开始了新生活。', 'idiom', 'advanced'),
('every cloud has a silver lining', '黑暗中总有一线光明', '坏事中总有好的一面', 'Don''t worry, every cloud has a silver lining.', '别担心，黑暗中总有一线光明。', 'idiom', 'advanced'),
('better late than never', '迟到总比不到好', '虽然晚了，但还是做了比不做好', 'You finally called me back - better late than never!', '你终于回电话了——迟到总比不到好！', 'colloquial', 'intermediate'),
('when pigs fly', '绝不可能', '用来表示某事永远不会发生', 'He''ll clean his room when pigs fly.', '他永远不会打扫房间的。', 'colloquial', 'intermediate'),
('the early bird catches the worm', '早起的鸟儿有虫吃', '早起或提前行动的人会得到好处', 'She always arrives first because the early bird catches the worm.', '她总是第一个到达，因为早起的鸟儿有虫吃。', 'idiom', 'intermediate'),
('don''t put all your eggs in one basket', '不要孤注一掷', '不要把所有希望寄托在一件事上', 'Invest in different stocks - don''t put all your eggs in one basket.', '投资不同的股票——不要孤注一掷。', 'business', 'advanced'),
('actions speak louder than words', '行动胜于言语', '实际行动比言语更重要', 'He says he cares, but actions speak louder than words.', '他说他在乎，但行动胜于言语。', 'idiom', 'intermediate'),
('practice makes perfect', '熟能生巧', '通过反复练习可以达到完美', 'Keep playing piano - practice makes perfect.', '继续弹钢琴——熟能生巧。', 'colloquial', 'beginner'),
('time flies when you''re having fun', '快乐时光总是短暂', '享受时光过得很快', 'We talked all night - time flies when you''re having fun.', '我们聊了一整夜——快乐时光总是短暂。', 'colloquial', 'intermediate'),
('a blessing in disguise', '因祸得福', '看似坏事实际上是好事', 'Losing that job was a blessing in disguise.', '丢掉那份工作其实是因祸得福。', 'idiom', 'advanced'),
('break a leg', '祝你好运', '用于祝愿某人成功，特别是在表演前', 'Break a leg at your audition today!', '祝你今天试镜好运！', 'colloquial', 'intermediate'),
('hang in there', '坚持住', '鼓励某人在困难时期坚持下去', 'I know it''s tough, but hang in there.', '我知道很艰难，但要坚持住。', 'colloquial', 'intermediate'),
('it''s not rocket science', '这不是什么难事', '表示某事很容易理解或完成', 'Learning to cook is not rocket science.', '学做饭不是什么难事。', 'colloquial', 'intermediate'),
('kill two birds with one stone', '一箭双雕', '一次行动达成两个目标', 'I''ll visit the bank and post office - kill two birds with one stone.', '我要去银行和邮局——一箭双雕。', 'idiom', 'intermediate'),
('the best of both worlds', '两全其美', '同时享受两种好处', 'Working from home gives me the best of both worlds.', '在家工作让我两全其美。', 'colloquial', 'intermediate'),
('step up to the plate', '承担责任', '准备好面对挑战或承担责任', 'When the manager quit, she stepped up to the plate.', '当经理辞职时，她承担起了责任。', 'business', 'advanced'),
('get back on the horse', '重新开始', '在失败后再次尝试', 'After the accident, he got back on the horse and started driving again.', '事故后，他重新开始并再次开车。', 'idiom', 'advanced'),
('Rome wasn''t built in a day', '罗马不是一天建成的', '重要的事情需要时间才能完成', 'Learning a language takes time - Rome wasn''t built in a day.', '学习语言需要时间——罗马不是一天建成的。', 'idiom', 'intermediate');