-- 继续插入剩余的英语名言
INSERT INTO english_quotes (quote_text, quote_translation, author, author_translation, difficulty_level, category) VALUES
('The only way to do great work is to love what you do.', '做出优秀工作的唯一方法就是热爱你所做的事情。', 'Steve Jobs', '史蒂夫·乔布斯', 'intermediate', 'motivational'),
('Life is what happens to you while you''re busy making other plans.', '生活就是当你忙于制定其他计划时发生在你身上的事情。', 'John Lennon', '约翰·列侬', 'intermediate', 'motivational'),
('The future belongs to those who believe in the beauty of their dreams.', '未来属于那些相信梦想之美的人。', 'Eleanor Roosevelt', '埃莉诺·罗斯福', 'intermediate', 'motivational'),
('It is during our darkest moments that we must focus to see the light.', '正是在我们最黑暗的时刻，我们必须集中精力去看见光明。', 'Aristotle', '亚里士多德', 'advanced', 'motivational'),
('The way to get started is to quit talking and begin doing.', '开始行动的方法就是停止空谈，开始实干。', 'Walt Disney', '沃尔特·迪斯尼', 'intermediate', 'motivational'),
('Don''t let yesterday take up too much of today.', '不要让昨天占据今天太多的时间。', 'Will Rogers', '威尔·罗杰斯', 'beginner', 'motivational'),
('You learn more from failure than from success.', '你从失败中学到的比从成功中学到的更多。', 'Unknown', '佚名', 'intermediate', 'motivational'),
('If you are working on something exciting that you really care about, you don''t have to be pushed.', '如果你正在做一些你真正关心的令人兴奋的事情，你就不需要被推动。', 'Steve Jobs', '史蒂夫·乔布斯', 'advanced', 'motivational'),
('Don''t be afraid to give up the good to go for the great.', '不要害怕放弃好的去追求伟大的。', 'John D. Rockefeller', '约翰·D·洛克菲勒', 'intermediate', 'motivational'),
('The secret of success is to do the common thing uncommonly well.', '成功的秘诀是把平凡的事情做得异常出色。', 'John D. Rockefeller Jr.', '小约翰·D·洛克菲勒', 'advanced', 'motivational'),
('I find that the harder I work, the more luck I seem to have.', '我发现我越努力工作，我就越幸运。', 'Thomas Jefferson', '托马斯·杰斐逊', 'intermediate', 'motivational'),
('Don''t let the fear of losing be greater than the excitement of winning.', '不要让对失败的恐惧超过对胜利的兴奋。', 'Robert Kiyosaki', '罗伯特·清崎', 'intermediate', 'motivational'),
('If you really look closely, most overnight successes took a long time.', '如果你真的仔细观察，大多数一夜成功都需要很长时间。', 'Steve Jobs', '史蒂夫·乔布斯', 'advanced', 'motivational'),
('The way I see it, if you want the rainbow, you gotta put up with the rain.', '在我看来，如果你想要彩虹，你就得忍受雨水。', 'Dolly Parton', '多莉·帕顿', 'intermediate', 'motivational'),
('Some people want it to happen, some wish it would happen, others make it happen.', '有些人希望它发生，有些人希望它会发生，另一些人让它发生。', 'Michael Jordan', '迈克尔·乔丹', 'intermediate', 'motivational'),
('Great minds discuss ideas; average minds discuss events; small minds discuss people.', '伟大的心灵讨论思想；平庸的心灵讨论事件；渺小的心灵讨论人。', 'Eleanor Roosevelt', '埃莉诺·罗斯福', 'advanced', 'motivational'),
('It does not matter how slowly you go as long as you do not stop.', '只要你不停下，走得多慢都没关系。', 'Confucius', '孔子', 'intermediate', 'motivational'),
('Everything you''ve ever wanted is on the other side of fear.', '你想要的一切都在恐惧的另一边。', 'George Addair', '乔治·阿代尔', 'intermediate', 'motivational'),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', '成功不是终点，失败不是致命的：重要的是继续前进的勇气。', 'Winston Churchill', '温斯顿·丘吉尔', 'advanced', 'motivational'),
('The only person you are destined to become is the person you decide to be.', '你注定要成为的唯一的人是你决定成为的人。', 'Ralph Waldo Emerson', '拉尔夫·沃尔多·爱默生', 'advanced', 'motivational'),
('Your limitation—it''s only your imagination.', '你的限制——只是你的想象。', 'Unknown', '佚名', 'beginner', 'motivational'),
('Push yourself, because no one else is going to do it for you.', '推动自己，因为没有人会为你做这件事。', 'Unknown', '佚名', 'intermediate', 'motivational'),
('Great things never come from comfort zones.', '伟大的事情从来不会来自舒适区。', 'Unknown', '佚名', 'intermediate', 'motivational'),
('Dream it. Wish it. Do it.', '梦想它。希望它。去做它。', 'Unknown', '佚名', 'beginner', 'motivational'),
('Success doesn''t just find you. You have to go out and get it.', '成功不会主动找到你。你必须出去争取它。', 'Unknown', '佚名', 'intermediate', 'motivational'),
('The harder you work for something, the greater you''ll feel when you achieve it.', '你为某事越努力，当你实现它时你会感觉越棒。', 'Unknown', '佚名', 'intermediate', 'motivational'),
('Dream bigger. Do bigger.', '梦想更大。做得更大。', 'Unknown', '佚名', 'beginner', 'motivational'),
('Don''t stop when you''re tired. Stop when you''re done.', '当你累的时候不要停止。完成了再停止。', 'Unknown', '佚名', 'intermediate', 'motivational'),
('Wake up with determination. Go to bed with satisfaction.', '带着决心醒来。带着满足入睡。', 'Unknown', '佚名', 'intermediate', 'motivational'),
('Do something today that your future self will thank you for.', '今天做一些你未来的自己会感谢你的事情。', 'Unknown', '佚名', 'intermediate', 'motivational');