-- 插入更多英语名言 (总共至少35条)
INSERT INTO english_quotes (quote_text, quote_translation, author, author_translation, difficulty_level, category) VALUES
('The only way to do great work is to love what you do.', '做出优秀工作的唯一方法就是热爱你所做的事情。', 'Steve Jobs', '史蒂夫·乔布斯', 'intermediate', 'motivational'),
('Life is what happens to you while you''re busy making other plans.', '生活就是当你忙于制定其他计划时发生在你身上的事情。', 'John Lennon', '约翰·列侬', 'intermediate', 'life'),
('The future belongs to those who believe in the beauty of their dreams.', '未来属于那些相信梦想之美的人。', 'Eleanor Roosevelt', '埃莉诺·罗斯福', 'intermediate', 'dreams'),
('It is during our darkest moments that we must focus to see the light.', '正是在我们最黑暗的时刻，我们必须集中精力去看见光明。', 'Aristotle', '亚里士多德', 'advanced', 'perseverance'),
('The way to get started is to quit talking and begin doing.', '开始行动的方法就是停止空谈，开始实干。', 'Walt Disney', '沃尔特·迪斯尼', 'intermediate', 'action'),
('Don''t let yesterday take up too much of today.', '不要让昨天占据今天太多的时间。', 'Will Rogers', '威尔·罗杰斯', 'beginner', 'present'),
('You learn more from failure than from success.', '你从失败中学到的比从成功中学到的更多。', 'Unknown', '佚名', 'intermediate', 'learning'),
('If you are working on something exciting that you really care about, you don''t have to be pushed.', '如果你正在做一些你真正关心的令人兴奋的事情，你就不需要被推动。', 'Steve Jobs', '史蒂夫·乔布斯', 'advanced', 'passion'),
('Don''t be afraid to give up the good to go for the great.', '不要害怕放弃好的去追求伟大的。', 'John D. Rockefeller', '约翰·D·洛克菲勒', 'intermediate', 'excellence'),
('The secret of success is to do the common thing uncommonly well.', '成功的秘诀是把平凡的事情做得异常出色。', 'John D. Rockefeller Jr.', '小约翰·D·洛克菲勒', 'advanced', 'success'),
('I find that the harder I work, the more luck I seem to have.', '我发现我越努力工作，我就越幸运。', 'Thomas Jefferson', '托马斯·杰斐逊', 'intermediate', 'hard work'),
('Don''t let the fear of losing be greater than the excitement of winning.', '不要让对失败的恐惧超过对胜利的兴奋。', 'Robert Kiyosaki', '罗伯特·清崎', 'intermediate', 'courage'),
('If you really look closely, most overnight successes took a long time.', '如果你真的仔细观察，大多数一夜成功都需要很长时间。', 'Steve Jobs', '史蒂夫·乔布斯', 'advanced', 'patience'),
('The way I see it, if you want the rainbow, you gotta put up with the rain.', '在我看来，如果你想要彩虹，你就得忍受雨水。', 'Dolly Parton', '多莉·帕顿', 'intermediate', 'perseverance'),
('Some people want it to happen, some wish it would happen, others make it happen.', '有些人希望它发生，有些人希望它会发生，另一些人让它发生。', 'Michael Jordan', '迈克尔·乔丹', 'intermediate', 'action'),
('Great minds discuss ideas; average minds discuss events; small minds discuss people.', '伟大的心灵讨论思想；平庸的心灵讨论事件；渺小的心灵讨论人。', 'Eleanor Roosevelt', '埃莉诺·罗斯福', 'advanced', 'wisdom'),
('It does not matter how slowly you go as long as you do not stop.', '只要你不停下，走得多慢都没关系。', 'Confucius', '孔子', 'intermediate', 'persistence'),
('Everything you''ve ever wanted is on the other side of fear.', '你想要的一切都在恐惧的另一边。', 'George Addair', '乔治·阿代尔', 'intermediate', 'courage'),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', '成功不是终点，失败不是致命的：重要的是继续前进的勇气。', 'Winston Churchill', '温斯顿·丘吉尔', 'advanced', 'resilience'),
('The only person you are destined to become is the person you decide to be.', '你注定要成为的唯一的人是你决定成为的人。', 'Ralph Waldo Emerson', '拉尔夫·沃尔多·爱默生', 'advanced', 'self-determination'),
('Your limitation—it''s only your imagination.', '你的限制——只是你的想象。', 'Unknown', '佚名', 'beginner', 'potential'),
('Push yourself, because no one else is going to do it for you.', '推动自己，因为没有人会为你做这件事。', 'Unknown', '佚名', 'intermediate', 'self-motivation'),
('Great things never come from comfort zones.', '伟大的事情从来不会来自舒适区。', 'Unknown', '佚名', 'intermediate', 'growth'),
('Dream it. Wish it. Do it.', '梦想它。希望它。去做它。', 'Unknown', '佚名', 'beginner', 'action'),
('Success doesn''t just find you. You have to go out and get it.', '成功不会主动找到你。你必须出去争取它。', 'Unknown', '佚名', 'intermediate', 'effort'),
('The harder you work for something, the greater you''ll feel when you achieve it.', '你为某事越努力，当你实现它时你会感觉越棒。', 'Unknown', '佚名', 'intermediate', 'satisfaction'),
('Dream bigger. Do bigger.', '梦想更大。做得更大。', 'Unknown', '佚名', 'beginner', 'ambition'),
('Don''t stop when you''re tired. Stop when you''re done.', '当你累的时候不要停止。完成了再停止。', 'Unknown', '佚名', 'intermediate', 'perseverance'),
('Wake up with determination. Go to bed with satisfaction.', '带着决心醒来。带着满足入睡。', 'Unknown', '佚名', 'intermediate', 'daily motivation'),
('Do something today that your future self will thank you for.', '今天做一些你未来的自己会感谢你的事情。', 'Unknown', '佚名', 'intermediate', 'future thinking');

-- 插入更多英语单词 (总共至少40个)
INSERT INTO english_words (word, pronunciation, meaning, example_sentence, example_translation, word_type, difficulty_level, frequency_rank) VALUES
('adventure', '/ədˈventʃər/', '冒险，奇遇', 'Life is an adventure waiting to be explored.', '生活是一场等待探索的冒险。', 'noun', 'intermediate', 6),
('beautiful', '/ˈbjuːtɪfl/', '美丽的，漂亮的', 'The sunset was absolutely beautiful tonight.', '今晚的日落绝对美丽。', 'adjective', 'beginner', 7),
('confident', '/ˈkɒnfɪdənt/', '自信的，确信的', 'She felt confident about her presentation.', '她对自己的演讲感到自信。', 'adjective', 'intermediate', 8),
('determined', '/dɪˈtɜːmɪnd/', '坚决的，下定决心的', 'He was determined to finish the marathon.', '他决心完成马拉松比赛。', 'adjective', 'intermediate', 9),
('enthusiastic', '/ɪnˌθjuːziˈæstɪk/', '热情的，热心的', 'The teacher was enthusiastic about the new project.', '老师对新项目很热心。', 'adjective', 'advanced', 10),
('flexible', '/ˈfleksəbl/', '灵活的，可弯曲的', 'You need to be flexible in your approach.', '你需要在方法上灵活一些。', 'adjective', 'intermediate', 11),
('generous', '/ˈdʒenərəs/', '慷慨的，大方的', 'She was generous with her time and help.', '她在时间和帮助上很慷慨。', 'adjective', 'intermediate', 12),
('honest', '/ˈɒnɪst/', '诚实的，正直的', 'He gave an honest answer to the question.', '他对这个问题给出了诚实的答案。', 'adjective', 'beginner', 13),
('innovative', '/ˈɪnəveɪtɪv/', '创新的，革新的', 'The company is known for its innovative products.', '这家公司以其创新产品而闻名。', 'adjective', 'advanced', 14),
('journey', '/ˈdʒɜːni/', '旅程，旅行', 'Learning a language is a long journey.', '学习语言是一个漫长的旅程。', 'noun', 'intermediate', 15),
('knowledge', '/ˈnɒlɪdʒ/', '知识，学问', 'Knowledge is power in today''s world.', '在当今世界，知识就是力量。', 'noun', 'intermediate', 16),
('leadership', '/ˈliːdəʃɪp/', '领导力，领导地位', 'Good leadership is essential for team success.', '良好的领导力对团队成功至关重要。', 'noun', 'advanced', 17),
('motivation', '/ˌməʊtɪˈveɪʃn/', '动机，积极性', 'His motivation comes from helping others.', '他的动力来自于帮助他人。', 'noun', 'advanced', 18),
('natural', '/ˈnætʃrəl/', '自然的，天然的', 'She has a natural talent for music.', '她有音乐天赋。', 'adjective', 'intermediate', 19),
('opportunity', '/ˌɒpəˈtjuːnəti/', '机会，时机', 'This job is a great opportunity for growth.', '这份工作是成长的好机会。', 'noun', 'intermediate', 20),
('passionate', '/ˈpæʃənət/', '热情的，激情的', 'She is passionate about environmental protection.', '她对环境保护充满热情。', 'adjective', 'advanced', 21),
('quality', '/ˈkwɒləti/', '质量，品质', 'The quality of this product is excellent.', '这个产品的质量很好。', 'noun', 'intermediate', 22),
('responsibility', '/rɪˌspɒnsəˈbɪləti/', '责任，职责', 'Taking care of pets is a big responsibility.', '照顾宠物是一个很大的责任。', 'noun', 'advanced', 23),
('solution', '/səˈluːʃn/', '解决方案，答案', 'We need to find a solution to this problem.', '我们需要找到这个问题的解决方案。', 'noun', 'intermediate', 24),
('tradition', '/trəˈdɪʃn/', '传统，惯例', 'Family dinner is an important tradition for us.', '家庭聚餐对我们来说是重要的传统。', 'noun', 'intermediate', 25),
('unique', '/juˈniːk/', '独特的，唯一的', 'Everyone has their own unique personality.', '每个人都有自己独特的个性。', 'adjective', 'intermediate', 26),
('valuable', '/ˈvæljuəbl/', '有价值的，宝贵的', 'Time is the most valuable resource we have.', '时间是我们拥有的最宝贵的资源。', 'adjective', 'intermediate', 27),
('wisdom', '/ˈwɪzdəm/', '智慧，明智', 'Age often brings wisdom and experience.', '年龄往往带来智慧和经验。', 'noun', 'advanced', 28),
('excellent', '/ˈeksələnt/', '优秀的，卓越的', 'Your performance was excellent today.', '你今天的表现很出色。', 'adjective', 'intermediate', 29),
('creative', '/kriˈeɪtɪv/', '创造性的，有创意的', 'She has a very creative approach to problem-solving.', '她在解决问题方面有很有创意的方法。', 'adjective', 'intermediate', 30),
('peaceful', '/ˈpiːsfl/', '和平的，平静的', 'The garden is a peaceful place to relax.', '花园是一个放松的宁静之地。', 'adjective', 'intermediate', 31),
('powerful', '/ˈpaʊəfl/', '强大的，有力的', 'Education is a powerful tool for change.', '教育是变革的有力工具。', 'adjective', 'intermediate', 32),
('reliable', '/rɪˈlaɪəbl/', '可靠的，可信赖的', 'He is a reliable friend who always helps.', '他是一个总是帮助别人的可靠朋友。', 'adjective', 'intermediate', 33),
('successful', '/səkˈsesfl/', '成功的，有成就的', 'Hard work often leads to successful outcomes.', '努力工作往往能带来成功的结果。', 'adjective', 'intermediate', 34),
('wonderful', '/ˈwʌndəfl/', '精彩的，极好的', 'We had a wonderful time at the party.', '我们在聚会上玩得很开心。', 'adjective', 'beginner', 35);

-- 插入更多英语短语 (总共至少35个)
INSERT INTO english_phrases (phrase_english, phrase_chinese, meaning_explanation, example_sentence, example_translation, category, difficulty_level) VALUES
('break the ice', '打破僵局', '开始对话或缓解紧张气氛', 'He told a joke to break the ice at the meeting.', '他讲了个笑话来打破会议上的僵局。', 'social', 'intermediate'),
('piece of cake', '小菜一碟', '非常容易的事情', 'The math test was a piece of cake for her.', '数学考试对她来说是小菜一碟。', 'general', 'intermediate'),
('hit the books', '努力学习', '开始认真学习或阅读', 'I need to hit the books for my final exams.', '我需要为期末考试努力学习。', 'education', 'intermediate'),
('under the weather', '身体不适', '感觉生病或不舒服', 'I''m feeling a bit under the weather today.', '我今天感觉有点不舒服。', 'health', 'intermediate'),
('spill the beans', '泄露秘密', '无意中透露秘密信息', 'Don''t spill the beans about the surprise party.', '不要泄露惊喜派对的秘密。', 'general', 'intermediate'),
('cost an arm and a leg', '很昂贵', '价格非常高昂', 'That designer bag costs an arm and a leg.', '那个设计师包包非常昂贵。', 'money', 'advanced'),
('once in a blue moon', '千载难逢', '非常罕见或很少发生', 'We only see each other once in a blue moon.', '我们很少见面。', 'time', 'advanced'),
('the ball is in your court', '该你行动了', '轮到你做决定或采取行动', 'I''ve made my offer, now the ball is in your court.', '我已经提出了我的条件，现在该你行动了。', 'responsibility', 'advanced'),
('let the cat out of the bag', '泄露秘密', '意外地透露了秘密', 'She let the cat out of the bag about the promotion.', '她无意中泄露了晋升的秘密。', 'general', 'intermediate'),
('bite the bullet', '咬紧牙关', '勇敢面对困难或不愉快的情况', 'We have to bite the bullet and cut costs.', '我们必须咬紧牙关削减成本。', 'courage', 'advanced'),
('go the extra mile', '付出额外努力', '做超出期望的事情', 'She always goes the extra mile for her customers.', '她总是为顾客付出额外的努力。', 'effort', 'intermediate'),
('keep your chin up', '保持乐观', '在困难时期保持积极态度', 'Keep your chin up, things will get better.', '保持乐观，事情会好转的。', 'encouragement', 'intermediate'),
('turn over a new leaf', '重新开始', '改变行为，开始新的生活方式', 'After the accident, he turned over a new leaf.', '事故后，他重新开始了新生活。', 'change', 'advanced'),
('every cloud has a silver lining', '黑暗中总有一线光明', '坏事中总有好的一面', 'Don''t worry, every cloud has a silver lining.', '别担心，黑暗中总有一线光明。', 'optimism', 'advanced'),
('better late than never', '迟到总比不到好', '虽然晚了，但还是做了比不做好', 'You finally called me back - better late than never!', '你终于回电话了——迟到总比不到好！', 'time', 'intermediate'),
('when pigs fly', '绝不可能', '用来表示某事永远不会发生', 'He''ll clean his room when pigs fly.', '他永远不会打扫房间的。', 'impossibility', 'intermediate'),
('the early bird catches the worm', '早起的鸟儿有虫吃', '早起或提前行动的人会得到好处', 'She always arrives first because the early bird catches the worm.', '她总是第一个到达，因为早起的鸟儿有虫吃。', 'success', 'intermediate'),
('don''t put all your eggs in one basket', '不要孤注一掷', '不要把所有希望寄托在一件事上', 'Invest in different stocks - don''t put all your eggs in one basket.', '投资不同的股票——不要孤注一掷。', 'strategy', 'advanced'),
('actions speak louder than words', '行动胜于言语', '实际行动比言语更重要', 'He says he cares, but actions speak louder than words.', '他说他在乎，但行动胜于言语。', 'behavior', 'intermediate'),
('practice makes perfect', '熟能生巧', '通过反复练习可以达到完美', 'Keep playing piano - practice makes perfect.', '继续弹钢琴——熟能生巧。', 'learning', 'beginner'),
('time flies when you''re having fun', '快乐时光总是短暂', '享受时光过得很快', 'We talked all night - time flies when you''re having fun.', '我们聊了一整夜——快乐时光总是短暂。', 'time', 'intermediate'),
('a blessing in disguise', '因祸得福', '看似坏事实际上是好事', 'Losing that job was a blessing in disguise.', '丢掉那份工作其实是因祸得福。', 'perspective', 'advanced'),
('break a leg', '祝你好运', '用于祝愿某人成功，特别是在表演前', 'Break a leg at your audition today!', '祝你今天试镜好运！', 'encouragement', 'intermediate'),
('hang in there', '坚持住', '鼓励某人在困难时期坚持下去', 'I know it''s tough, but hang in there.', '我知道很艰难，但要坚持住。', 'encouragement', 'intermediate'),
('it''s not rocket science', '这不是什么难事', '表示某事很容易理解或完成', 'Learning to cook is not rocket science.', '学做饭不是什么难事。', 'simplicity', 'intermediate'),
('kill two birds with one stone', '一箭双雕', '一次行动达成两个目标', 'I''ll visit the bank and post office - kill two birds with one stone.', '我要去银行和邮局——一箭双雕。', 'efficiency', 'intermediate'),
('the best of both worlds', '两全其美', '同时享受两种好处', 'Working from home gives me the best of both worlds.', '在家工作让我两全其美。', 'advantage', 'intermediate'),
('step up to the plate', '承担责任', '准备好面对挑战或承担责任', 'When the manager quit, she stepped up to the plate.', '当经理辞职时，她承担起了责任。', 'responsibility', 'advanced'),
('get back on the horse', '重新开始', '在失败后再次尝试', 'After the accident, he got back on the horse and started driving again.', '事故后，他重新开始并再次开车。', 'perseverance', 'advanced'),
('Rome wasn''t built in a day', '罗马不是一天建成的', '重要的事情需要时间才能完成', 'Learning a language takes time - Rome wasn''t built in a day.', '学习语言需要时间——罗马不是一天建成的。', 'patience', 'intermediate');

-- 插入更多英语听力材料 (总共至少20个)
INSERT INTO english_listening (title, content, translation, difficulty_level, topic, estimated_duration, word_count) VALUES
('Morning Routine', 'I wake up at seven o''clock every morning. First, I brush my teeth and wash my face. Then I have breakfast with my family. After breakfast, I get dressed and go to work. I usually arrive at the office by nine o''clock.', '我每天早上七点醒来。首先，我刷牙洗脸。然后和家人一起吃早餐。早餐后，我穿好衣服去上班。我通常九点前到达办公室。', 'beginner', 'daily life', 45, 46),
('Weekend Plans', 'This weekend I have many exciting plans. On Saturday morning, I will visit the local farmers market with my friends. We plan to buy fresh vegetables and fruits. In the afternoon, we will have a picnic in the park. On Sunday, I want to read a good book and relax at home.', '这个周末我有很多令人兴奋的计划。周六上午，我将和朋友们一起参观当地的农贸市场。我们计划购买新鲜的蔬菜和水果。下午，我们将在公园野餐。周日，我想读一本好书，在家放松。', 'intermediate', 'leisure', 60, 61),
('Healthy Eating', 'Eating a balanced diet is very important for our health. We should eat plenty of fruits and vegetables every day. Whole grains, lean proteins, and healthy fats are also essential. It''s better to limit processed foods and sugary drinks. Drinking enough water throughout the day helps our body function properly.', '均衡饮食对我们的健康非常重要。我们应该每天吃大量的水果和蔬菜。全谷物、瘦蛋白质和健康脂肪也是必需的。最好限制加工食品和含糖饮料。全天喝足够的水有助于我们的身体正常运作。', 'intermediate', 'health', 65, 65),
('Climate Change', 'Climate change is one of the most pressing issues of our time. Rising global temperatures are causing more frequent extreme weather events. Sea levels are rising, threatening coastal communities worldwide. Governments and individuals must work together to reduce greenhouse gas emissions and transition to renewable energy sources.', '气候变化是我们时代最紧迫的问题之一。全球气温上升导致极端天气事件更加频繁。海平面上升，威胁着世界各地的沿海社区。政府和个人必须共同努力减少温室气体排放，转向可再生能源。', 'advanced', 'environment', 70, 70),
('Technology in Education', 'Technology has revolutionized the way we learn and teach. Online platforms make education accessible to people around the world. Students can now attend virtual classes and access digital libraries. However, we must ensure that technology enhances rather than replaces human interaction in the learning process.', '技术已经彻底改变了我们学习和教学的方式。在线平台使世界各地的人们都能接受教育。学生现在可以参加虚拟课程并访问数字图书馆。然而，我们必须确保技术是增强而不是取代学习过程中的人际互动。', 'advanced', 'education', 75, 75),
('Family Traditions', 'Every family has special traditions that bring them together. In my family, we gather every Sunday for dinner. My grandmother always cooks our favorite meal. We share stories about our week and make plans for the future. These moments create lasting memories and strengthen our family bonds.', '每个家庭都有让他们团聚的特殊传统。在我家，我们每个周日都聚在一起吃晚饭。我的祖母总是做我们最喜欢的饭菜。我们分享一周的故事并为未来制定计划。这些时刻创造持久的回忆并加强我们的家庭纽带。', 'intermediate', 'family', 55, 55),
('Exercise Benefits', 'Regular exercise has many benefits for both physical and mental health. It helps maintain a healthy weight and strengthens muscles and bones. Exercise also improves mood and reduces stress. Even thirty minutes of moderate activity daily can make a significant difference in your overall well-being.', '定期锻炼对身心健康都有很多好处。它有助于保持健康的体重并强化肌肉和骨骼。运动还能改善情绪并减少压力。即使每天三十分钟的适度活动也能让你的整体健康状况发生显著变化。', 'intermediate', 'health', 50, 50),
('Travel Experiences', 'Traveling opens our minds to new cultures and perspectives. When I visited Japan last year, I was amazed by the kindness of the local people. I tried traditional foods and learned about ancient customs. These experiences taught me to appreciate diversity and be more open-minded about different ways of life.', '旅行让我们的思想接触新的文化和观点。去年我访问日本时，当地人的善良让我惊讶。我尝试了传统食物并了解了古老的习俗。这些经历教会我欣赏多样性并对不同的生活方式更加开放。', 'intermediate', 'travel', 65, 65),
('Career Development', 'Building a successful career requires continuous learning and adaptation. In today''s rapidly changing job market, it''s important to develop both technical and soft skills. Networking with professionals in your field can open new opportunities. Remember that career growth is a marathon, not a sprint.', '建立成功的职业生涯需要持续学习和适应。在当今快速变化的就业市场中，发展技术技能和软技能都很重要。与你所在领域的专业人士建立网络可以开启新的机会。记住职业发展是马拉松，不是短跑。', 'advanced', 'career', 70, 70),
('Environmental Protection', 'Protecting our environment is everyone''s responsibility. Simple actions like recycling, reducing waste, and using public transportation can make a big difference. We should also support companies that prioritize sustainability. By working together, we can create a cleaner, healthier planet for future generations.', '保护我们的环境是每个人的责任。像回收利用、减少浪费和使用公共交通这样的简单行动可以产生很大的影响。我们还应该支持优先考虑可持续发展的公司。通过共同努力，我们可以为后代创造一个更清洁、更健康的星球。', 'intermediate', 'environment', 60, 60),
('Time Management', 'Effective time management is crucial for success in both personal and professional life. Start by identifying your priorities and setting clear goals. Use tools like calendars and to-do lists to organize your tasks. Remember to schedule breaks and maintain a healthy work-life balance.', '有效的时间管理对个人和职业生活的成功都至关重要。首先要确定你的优先事项并设定明确的目标。使用日历和待办事项清单等工具来组织你的任务。记住要安排休息时间并保持健康的工作生活平衡。', 'intermediate', 'productivity', 55, 55),
('Friendship Values', 'True friendship is one of life''s greatest treasures. Good friends support each other through both happy and difficult times. They listen without judgment and offer honest advice when needed. Building strong friendships requires trust, respect, and mutual understanding. Invest time in nurturing these valuable relationships.', '真正的友谊是人生最大的财富之一。好朋友在快乐和困难时期都相互支持。他们不带评判地倾听，在需要时提供诚实的建议。建立牢固的友谊需要信任、尊重和相互理解。投入时间培养这些宝贵的关系。', 'intermediate', 'relationships', 65, 65),
('Digital Wellness', 'In our digital age, it''s important to maintain a healthy relationship with technology. Set boundaries for screen time and take regular breaks from devices. Practice mindful usage by being intentional about when and why you use technology. Create tech-free zones in your home to encourage face-to-face interactions and relaxation.', '在我们的数字时代，与技术保持健康的关系很重要。设定屏幕时间的界限并定期从设备中休息。通过有意识地决定何时以及为什么使用技术来练习正念使用。在家中创建无技术区域以鼓励面对面的互动和放松。', 'advanced', 'technology', 70, 70),
('Learning Languages', 'Learning a new language opens doors to new opportunities and experiences. It improves cognitive function and enhances cultural understanding. Start with basic vocabulary and simple phrases. Practice speaking with native speakers whenever possible. Be patient with yourself and celebrate small victories along the way.', '学习新语言为新的机会和体验打开大门。它改善认知功能并增强文化理解。从基础词汇和简单短语开始。尽可能与母语人士练习口语。对自己要有耐心，并庆祝途中的小胜利。', 'intermediate', 'education', 60, 60),
('Stress Management', 'Managing stress effectively is essential for maintaining good health and well-being. Identify your stress triggers and develop healthy coping strategies. Deep breathing exercises, meditation, and regular physical activity can help reduce stress levels. Don''t hesitate to seek professional help when stress becomes overwhelming.', '有效管理压力对维持良好的健康和福祉至关重要。识别你的压力触发因素并制定健康的应对策略。深呼吸练习、冥想和定期体育活动可以帮助减少压力水平。当压力变得难以承受时，不要犹豫寻求专业帮助。', 'intermediate', 'health', 65, 65);