-- 重新插入英语听力材料 (使用正确的话题)
INSERT INTO english_listening (title, content, translation, difficulty_level, topic, estimated_duration, word_count) VALUES
('Morning Routine', 'I wake up at seven o''clock every morning. First, I brush my teeth and wash my face. Then I have breakfast with my family. After breakfast, I get dressed and go to work. I usually arrive at the office by nine o''clock.', '我每天早上七点醒来。首先，我刷牙洗脸。然后和家人一起吃早餐。早餐后，我穿好衣服去上班。我通常九点前到达办公室。', 'beginner', 'general', 45, 46),
('Weekend Plans', 'This weekend I have many exciting plans. On Saturday morning, I will visit the local farmers market with my friends. We plan to buy fresh vegetables and fruits. In the afternoon, we will have a picnic in the park. On Sunday, I want to read a good book and relax at home.', '这个周末我有很多令人兴奋的计划。周六上午，我将和朋友们一起参观当地的农贸市场。我们计划购买新鲜的蔬菜和水果。下午，我们将在公园野餐。周日，我想读一本好书，在家放松。', 'intermediate', 'general', 60, 61),
('Healthy Eating', 'Eating a balanced diet is very important for our health. We should eat plenty of fruits and vegetables every day. Whole grains, lean proteins, and healthy fats are also essential. It''s better to limit processed foods and sugary drinks. Drinking enough water throughout the day helps our body function properly.', '均衡饮食对我们的健康非常重要。我们应该每天吃大量的水果和蔬菜。全谷物、瘦蛋白质和健康脂肪也是必需的。最好限制加工食品和含糖饮料。全天喝足够的水有助于我们的身体正常运作。', 'intermediate', 'health', 65, 65),
('Climate Change', 'Climate change is one of the most pressing issues of our time. Rising global temperatures are causing more frequent extreme weather events. Sea levels are rising, threatening coastal communities worldwide. Governments and individuals must work together to reduce greenhouse gas emissions and transition to renewable energy sources.', '气候变化是我们时代最紧迫的问题之一。全球气温上升导致极端天气事件更加频繁。海平面上升，威胁着世界各地的沿海社区。政府和个人必须共同努力减少温室气体排放，转向可再生能源。', 'advanced', 'general', 70, 70),
('Technology in Education', 'Technology has revolutionized the way we learn and teach. Online platforms make education accessible to people around the world. Students can now attend virtual classes and access digital libraries. However, we must ensure that technology enhances rather than replaces human interaction in the learning process.', '技术已经彻底改变了我们学习和教学的方式。在线平台使世界各地的人们都能接受教育。学生现在可以参加虚拟课程并访问数字图书馆。然而，我们必须确保技术是增强而不是取代学习过程中的人际互动。', 'advanced', 'technology', 75, 75),
('Family Time', 'Every family has special traditions that bring them together. In my family, we gather every Sunday for dinner. My grandmother always cooks our favorite meal. We share stories about our week and make plans for the future. These moments create lasting memories and strengthen our family bonds.', '每个家庭都有让他们团聚的特殊传统。在我家，我们每个周日都聚在一起吃晚饭。我的祖母总是做我们最喜欢的饭菜。我们分享一周的故事并为未来制定计划。这些时刻创造持久的回忆并加强我们的家庭纽带。', 'intermediate', 'general', 55, 55),
('Exercise Benefits', 'Regular exercise has many benefits for both physical and mental health. It helps maintain a healthy weight and strengthens muscles and bones. Exercise also improves mood and reduces stress. Even thirty minutes of moderate activity daily can make a significant difference in your overall well-being.', '定期锻炼对身心健康都有很多好处。它有助于保持健康的体重并强化肌肉和骨骼。运动还能改善情绪并减少压力。即使每天三十分钟的适度活动也能让你的整体健康状况发生显著变化。', 'intermediate', 'health', 50, 50),
('Travel Stories', 'Traveling opens our minds to new cultures and perspectives. When I visited Japan last year, I was amazed by the kindness of the local people. I tried traditional foods and learned about ancient customs. These experiences taught me to appreciate diversity and be more open-minded about different ways of life.', '旅行让我们的思想接触新的文化和观点。去年我访问日本时，当地人的善良让我惊讶。我尝试了传统食物并了解了古老的习俗。这些经历教会我欣赏多样性并对不同的生活方式更加开放。', 'intermediate', 'general', 65, 65),
('Career Growth', 'Building a successful career requires continuous learning and adaptation. In today''s rapidly changing job market, it''s important to develop both technical and soft skills. Networking with professionals in your field can open new opportunities. Remember that career growth is a marathon, not a sprint.', '建立成功的职业生涯需要持续学习和适应。在当今快速变化的就业市场中，发展技术技能和软技能都很重要。与你所在领域的专业人士建立网络可以开启新的机会。记住职业发展是马拉松，不是短跑。', 'advanced', 'general', 70, 70),
('Environmental Care', 'Protecting our environment is everyone''s responsibility. Simple actions like recycling, reducing waste, and using public transportation can make a big difference. We should also support companies that prioritize sustainability. By working together, we can create a cleaner, healthier planet for future generations.', '保护我们的环境是每个人的责任。像回收利用、减少浪费和使用公共交通这样的简单行动可以产生很大的影响。我们还应该支持优先考虑可持续发展的公司。通过共同努力，我们可以为后代创造一个更清洁、更健康的星球。', 'intermediate', 'general', 60, 60),
('Time Planning', 'Effective time management is crucial for success in both personal and professional life. Start by identifying your priorities and setting clear goals. Use tools like calendars and to-do lists to organize your tasks. Remember to schedule breaks and maintain a healthy work-life balance.', '有效的时间管理对个人和职业生活的成功都至关重要。首先要确定你的优先事项并设定明确的目标。使用日历和待办事项清单等工具来组织你的任务。记住要安排休息时间并保持健康的工作生活平衡。', 'intermediate', 'general', 55, 55),
('Friendship', 'True friendship is one of life''s greatest treasures. Good friends support each other through both happy and difficult times. They listen without judgment and offer honest advice when needed. Building strong friendships requires trust, respect, and mutual understanding. Invest time in nurturing these valuable relationships.', '真正的友谊是人生最大的财富之一。好朋友在快乐和困难时期都相互支持。他们不带评判地倾听，在需要时提供诚实的建议。建立牢固的友谊需要信任、尊重和相互理解。投入时间培养这些宝贵的关系。', 'intermediate', 'general', 65, 65),
('Digital Life', 'In our digital age, it''s important to maintain a healthy relationship with technology. Set boundaries for screen time and take regular breaks from devices. Practice mindful usage by being intentional about when and why you use technology. Create tech-free zones in your home to encourage face-to-face interactions and relaxation.', '在我们的数字时代，与技术保持健康的关系很重要。设定屏幕时间的界限并定期从设备中休息。通过有意识地决定何时以及为什么使用技术来练习正念使用。在家中创建无技术区域以鼓励面对面的互动和放松。', 'advanced', 'technology', 70, 70),
('Language Learning', 'Learning a new language opens doors to new opportunities and experiences. It improves cognitive function and enhances cultural understanding. Start with basic vocabulary and simple phrases. Practice speaking with native speakers whenever possible. Be patient with yourself and celebrate small victories along the way.', '学习新语言为新的机会和体验打开大门。它改善认知功能并增强文化理解。从基础词汇和简单短语开始。尽可能与母语人士练习口语。对自己要有耐心，并庆祝途中的小胜利。', 'intermediate', 'general', 60, 60),
('Stress Relief', 'Managing stress effectively is essential for maintaining good health and well-being. Identify your stress triggers and develop healthy coping strategies. Deep breathing exercises, meditation, and regular physical activity can help reduce stress levels. Don''t hesitate to seek professional help when stress becomes overwhelming.', '有效管理压力对维持良好的健康和福祉至关重要。识别你的压力触发因素并制定健康的应对策略。深呼吸练习、冥想和定期体育活动可以帮助减少压力水平。当压力变得难以承受时，不要犹豫寻求专业帮助。', 'intermediate', 'health', 65, 65);