// Generated by Lovable's Supabase integration; env-var overrides added manually
// (a future Lovable sync may regenerate this file — restore the env lookups if so).
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer Vite env vars when provided (see .env.example); fall back to this project's
// publishable values. The URL and anon key are browser-safe by design — they ship in
// every client bundle and all data access is enforced by row-level security.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ?? "https://ihwgygkrmwpcyrxcyzgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlod2d5Z2tybXdwY3lyeGN5emdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODc3NzgsImV4cCI6MjA2NTU2Mzc3OH0.nzNnqg-wQ7SdsMSYQnvtR9_XXghgo6L8ddHRsTlIMXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
