// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihwgygkrmwpcyrxcyzgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlod2d5Z2tybXdwY3lyeGN5emdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODc3NzgsImV4cCI6MjA2NTU2Mzc3OH0.nzNnqg-wQ7SdsMSYQnvtR9_XXghgo6L8ddHRsTlIMXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);